development:
  adapter: async
#  adapter: redis
#  url: redis://polar-mountain-18909.herokuapp.com

test:
  adapter: async

production:
  adapter: redis
  url: redis://polar-mountain-18909.herokuapp.com